Phase01 -> main
Star-Academy/Summer1401-FE-Team01 pull request #3
Opened 2022-07-20 09:46 UTC by dorrin-sot

@sabaebrahimi

2022-07-20 11:54 UTC, sabaebrahimi requested changes

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/app.component.scss
> +.stack > .item {
<div style="direction: rtl">
از امکانات scss استفاده کنین.
مثلا : 

.stack {
//som style
.item {
}
}
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.html
> +<svg width="0" height="0">
<div style="direction: rtl">
این می تونه یک کامپوننت جدا بشه 
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +        border-radius: 4vw;
<div style="direction: rtl">
فکر نمی کنم vw چیز خوبی برای border-radius باشه :)
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +            font-size: 1.25vw;
<div style="direction: rtl">
برای فونت سایز، بهتره از درصد استفاده بشه
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +            //line-clamp: 2;
کد کامنت شده پاک شه

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +        font-family: "Cinema";
یه فونت جایگزین هم براش در نظر گرفته بشه

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +    color: #fff;
<div style="direction: rtl">
به جای #fff از white استفاده کنین 
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +        bottom: 4px;
<div style="direction: rtl">
اینجا از px استفاده نکنین 
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +    &:active:not(:disabled):before {
<div style="direction: rtl">
از امکانات scss استفاده کنین. اول از همه این &:active:not(:disabled) رو بذارید و داخلش :before , :after
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.scss
> +    gap: 6vw;
<div style="direction: rtl">
تو این بلاک از vw, px استفاده نکنین 
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.scss
> +        background-color: #2a2a2a;
<div style="direction: rtl">
چرا از متغیر هاتون استفاده نمی کنین؟ به جای هگز بهتره Hsl بذارید 
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.ts
> +    @Input() public games!: Array<Game>;
یه اینتر بعد این خط بزنین جدا شه و یه مقدار پیش فرض خالی هم برای جلوگیری از باگ بذارید براش

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.ts
> +        console.log(`nextSlide ${this.currentIndex}`);
<div style="direction: rtl">
وسط کدتون console.log نباشه 
</div>

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.ts
> +        console.log(`setIndex ${this.currentIndex}`);
پاک شه

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/footer/footer.component.html
> +    <div class="column">
شبکه های اجتماعی رو ببرید کامپوننت جدا

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/components/header/header.component.scss
> +        //align-items: flex-end;
کامنت پاک شه

2022-07-20 11:54 UTC, sabaebrahimi commented on src/app/models/game-image-data.ts
> +    public thumbnail(): string {
<div style="direction: rtl">
در مورد get تو امضای فانکشن ها تحقیق کنین. 
اینطوری می تونین بازنویسی کنین: 
public get thumbnail
</div>

2022-07-20 11:56 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +        border-radius: 4vw;
بنظرتون مقدار ثابت بهتره؟ چون درصد گوشه هارو قشنگ دایره ای نمیکرد

2022-07-20 12:07 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +        border-radius: 4vw;
<div style="direction:rtl">
استفاده از px , em هم خوبه 
</div>

2022-07-20 12:07 UTC, sabaebrahimi commented on src/app/components/carousel-item/carousel-item.component.scss
> +            font-size: 1.25vw;
یا em

2022-07-20 13:03 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +        bottom: 4px;
این یه حالت border نارنجی به کلفتی 4px اضافه میکنه برای دکمه. اشکال نداره همین بمونه؟

2022-07-20 13:10 UTC, dorrin-sot commented on src/app/components/carousel/carousel.component.scss
> +    gap: 6vw;
آخه باید مقداری استفاده کنم که از اونور توی carousel-item.component.scss داخل #uncharted، مقدار 6vw داخل transform برابر همین باشه که اگه درصد بزارم نمیشه. rem هم چون ثابته با کوچک بزرگ کردن صفحه فاصله بین اسلایدها بهم میریزه

2022-07-20 13:28 UTC, sabaebrahimi submitted a review, later dismissed

2022-07-20 13:32 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +        bottom: 4px;
البته 4px و عوض کردم به vw ولی یخورده زشته نوشته‌ش اگه اوکیه برگردونمش

2022-07-20 13:37 UTC, sabaebrahimi submitted a review, later dismissed

2022-07-20 14:31 UTC, dorrin-sot commented
@BijanEisapour

2022-07-20 14:31 UTC, sabaebrahimi submitted a review, later dismissed

2022-07-20 15:59 UTC, BijanEisapour requested changes

2022-07-20 15:59 UTC, BijanEisapour commented on .github/workflows/deploy-temp.yml
> +name: Deployment Workflow
چرا دو تا فایل دارید؟

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +    & > .item {
نیازی به & نیست

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +.column {
به نظر میرسه استایل‌های داخل این فایل global باشن 
باید بذاریدشون تو فایل styles.scss

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +    position: relative !important;
از important استفاده نکنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +        position: absolute !important;
از important استفاده نکنید
بقیه جاها اصلاح کنید 
دیگه نمیگم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +    font-family: "Yekan", fantasy;
این fantasy یه فونت سیستمی هست؟
اگه نه، یه فونت سیستمی به‌عنوان بکاپ اضافه کنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +    font-family: "Yekan", fantasy;
روی * نباید font-family بذارید 
به جاش رو html بذارید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.scss
> +.content-wrapper {
از این خط به بعد اگه از هر کدوم از استایل‌ها استفاده نکردید، پاکش کنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/app.component.ts
> +export const currentUser = new User('user123', '');
چرا اینجاس؟

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +#uncharted {
انقد از آیدی استفاده نکنید 
آیدی فقط واسه وقتیه که خیلی explicit میخواید بگید فلان المان یکتاست 
به جاش از کلاس استفاده کنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.html
> +        {{ game.avgRating.toFixed(1).persianNums() }}
به هیچ وجه از کاراکترهای فارسی استفاده نکنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +    aspect-ratio: calc(5 / 3);
نیاز به calc نیس 
مستیم تقسیم بنویسید 

```css
aspect-ratio: 5 / 3;
```

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +    aspect-ratio: calc(5 / 3);
ولی خب اصن چرا یه همچین نسبتی گذاشتید؟
استانداردش 16 به 9 ئه

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +    font-family: Yekan, serif;
نیاز نیس همه جا بذارید
فقط تو html بذارید؛ بقیه ازش ارث‌بری میکنن

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +        transition-property: height, width, filter;
حق ندارید width و height رو animate کنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +        bottom: -5%;
از inset-block-end و امثالهم استفاده کنید 
جاهای دیگه هم همینطور 
دیگه نمیگم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +        font-size: 10vw;
قابل قبول نیست 
به جاش از rem استفاده کنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +        padding-bottom: 2.5%;
padding-block-end

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +    padding-left: 20px;
پیکسل به هیچ وجه 
دیگه نمیگم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +.shiny-button {
تبدیل به کامپوننت شه چون کدش خیلی طولانیه

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +.shiny-button {
هر چند که توصیه میکنم کلاً برید سمت سادگی

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.html
> +    <app-carousel-item *ngFor="let game of games; index as i" [game]="game" [currentIndex]="currentIndex">
از index استفاده نکردید 
چرا تو for هست؟

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.ts
> +        }
وقتی if یه خطه، از آکلاد استفاده نکنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/components/social-media/social-media.component.html
> +        </li>
وقتی ندارید چرا گذاشتید؟

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/components/social-media/social-media.component.scss
> +  .bold {
بالاش enter بخوره

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/components/social-media/social-media.component.scss
> +    i {
بالاش enter بخوره

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/components/social-media/social-media.component.scss
> +    i:hover {
بالاش enter بخوره

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/components/social-media/social-media.component.scss
> +      color: 	hsl(287, 69%, 58%);
prettier

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        font-family: "Edu VIC WA NT Beginner";
انقد از فونت‌های مختلف استفاده نکنید 
تو کل سایت فقط از یه فونت استفاده کنید 
اونم یه فونت ساده و از نوع sans-serif باشه

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +        button {
به جای اینکه یه سری استایل‌ها رو همیشه به buttonها بدید و کد دوپلیکیت بزنید ...
یا استایل‌ها رو بذارید تو styles.scss که همه جا ازشون استفاده شه 
یا یه کامپوننت به اسم button بسازید که Input بگیره و variationهای مختلف داشته باشه

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +input:focus{
^

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +.input-box {
^

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +    i {
^

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +        color: coral;
به هیچ وجه 
فقط و فقط و فقط hsl

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/components/side-nav/side-nav.component.html
> +        <a href="#"><i class="fa-solid fa-gem"></i></a>
یا همه جا از اختصارش مثه far یا fas استفاده کنید یا همه جا از fa-regular و fa-solid استفاده کنید 

از طرفی فقط یکی از استایل‌های توپُر یا توخالی رو استفاده کنید 
اینجوری نباشه که نصف آیکن‌ها solid باشن، نصف دیگه regular

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/components/side-nav/side-nav.component.scss
> +    border-left: rgb(60, 53, 156, 0.5) solid;
از hsl استفاده کنید 
دیگه نمیگم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/components/header/header.component.scss
> +            color: 	hsl(246, 82%, 24%);
prettier

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/extensions/string.ts
> +export {};
کلاً این طرز کدنویسی مشکل دارم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/game-image-data.ts
> +        );
ها؟

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/game.ts
> +        return Array.from(this.ratings.values()).reduce((a, b) => a + b, 0) / this.ratings.size;
اینجور کارها رو تو فرانت انجام نمیدیم
بک انجام میده 
صرفاً نتیجه نهایی یعنی میانگین رو در اختیار شما میذاره

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/game.ts
> +        public shortTitle: string,
subtitle

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/user.ts
> +    public cart: Array<number> = []; // Game ids
کامنت نداریم مگر وقتی که مجبور باشیم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/pages/home/components/categories/categories.component.scss
> +        //row-gap: 2rem;
x

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/pages/home/components/categories/categories.component.scss
> +            //flex: 1 1 20%;
دیگه نمیگم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/pages/home/components/categories/categories.component.scss
> +        grid-template-rows: masonry;
هیچ مرورگری ساپورتش نمیکنه 
https://caniuse.com/?search=grid-masonry

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/pages/home/home.component.ts
> +}
تابع خارج از کامپوننت نداریم

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/game-image-data.ts
> +        public style: string = ''
اینا که نباید اینجا باشه 
یه چیز ثابته 
تو css باید باشه

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/game-image-data.ts
> +        public images: Array<string>,
فقط یه دونه image از سمت سرور میاد 
اگه چند تا دارید، با نرم‌افزاری چیزی یکیش کنید

2022-07-20 15:59 UTC, BijanEisapour commented on src/app/models/game-image-data.ts
> +        public images: Array<string>,
بنابراین اصن نیازی به این کلاس نیس و تو کلاس Game میتونید بذاریدش

2022-07-20 15:59 UTC, BijanEisapour commented on src/index.html
> +    "
قابل قبول نیس
بذاریدش تو styles.scss

2022-07-20 15:59 UTC, BijanEisapour commented on src/manifest.json
> +    "name": "Boilera by BijanProgrammer",
تو کل پروژه دنبال این اسم بگردید و عوضش کنید

2022-07-20 16:01 UTC, dorrin-sot commented on .github/workflows/deploy-temp.yml
> +name: Deployment Workflow
یکی برای main یکی قبل main (یه ذره توی اسم برنچ‌ها باهم فرق داشتن)

2022-07-20 16:10 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +#uncharted {
والا درمورد این آیتم یکتاس (البته تصمیم داشتم چندتا بازی دیگه هم به اسلایدها اضافه کنم و چون positionهاشون باهم فرق کنن نیاز بود آیتم‌های جدا باشن)

2022-07-20 16:13 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.html
> +        {{ game.avgRating.toFixed(1).persianNums() }}
ببخشید کلا استفاده نکنیم یا راهمون غلطه؟

2022-07-22 17:29 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +        transition-property: height, width, filter;
میتونیم all بزاریم؟

2022-07-22 17:33 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +        font-size: 10vw;
ببخشید آخه rem ثابته و اندازه اسلایدر با تغییر در سایز صفحه تغییر میکنه

2022-07-24 05:39 UTC, Negarnbkhti42 requested changes

2022-07-24 05:39 UTC, Negarnbkhti42 commented on src/app/components/footer/components/social-media/social-media.component.scss
> +                color: hsl(283deg 48% 66%);
بهتره که تغییر رنگ از افکتای هاور نباشه

2022-07-24 05:39 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.html
> +    <div class="topbar">
میشه از سمنتیک المنت nav استفاده کرد

2022-07-24 06:29 UTC, Negarnbkhti42 commented on src/app/pages/home/components/categories/categories.component.html
> +                <img [src]="category.image" alt="" />
alt تصویر خالی است

2022-07-24 06:36 UTC, Negarnbkhti42 approved these changes

2022-07-24 07:21 UTC, msrazavi approved these changes

2022-07-24 07:21 UTC, msrazavi commented on src/app/components/header/components/side-nav/side-nav.component.html
> +    </div>
برای آیکون‌ها تایتل اضافه شود.

2022-07-24 07:21 UTC, msrazavi commented on CONTRIBUTING.md
> +حال با رفتن به صفحه [Issues](https://github.com/Star-Academy/Summer1401-FE-Team01/issues) و انتخاب ایشو، Contribute کنید :)
متن بهتر و کاملتر

2022-07-24 07:21 UTC, msrazavi commented on src/app/components/carousel-item/carousel-item.component.html
> +            اضافه به سبد خرید
افزودن / اضافه کردن :)

2022-07-24 07:21 UTC, msrazavi commented on src/app/components/carousel/carousel.component.scss
> +}
استفاده از BEM

2022-07-24 07:21 UTC, msrazavi commented on src/app/components/footer/components/social-media/social-media.component.html
> +        </li>
لینک به جایی نیست

2022-07-24 07:21 UTC, msrazavi commented on src/app/components/footer/footer.component.html
> +        </button>
تایتل برای باتن

2022-07-24 07:21 UTC, msrazavi commented on src/app/components/header/header.component.html
> +        <a href="#"> <i class="far fa-user-group-crown"></i></a>
تایتل

2022-07-24 07:21 UTC, msrazavi commented on src/app/pages/home/components/categories/categories.component.ts
> +            image: 'assets/images/God-of-war.jpg',
عکس پرحجم

2022-07-24 08:38 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.html
> +        title="اسلاید بعد"
این خط و خط بعدی جا به جا بشن.

2022-07-24 08:38 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.ts
> +        if (addClass) bullet.classList.add('current');
<div style="direction=rtl">
در مورد ngClass مطالعه کنید. اگر شد با ngClass این مورد رو جایگزین بکنید. 
</div>

2022-07-24 08:38 UTC, sabaebrahimi commented on src/app/components/header/components/search-box/search-box.component.html
> +        placeholder="جستجو"
<div style="direction=rtl">
 این خط رو بیارید زیر خط 7
</div>

2022-07-24 08:38 UTC, sabaebrahimi commented on src/app/pages/home/components/categories/categories.component.scss
> +        li:hover {
<div style="direction=rtl">
این hover رو ببرید داخل بلوک بالا و با hover& بذارید.
</div>

2022-07-24 11:03 UTC, sabaebrahimi approved these changes

2022-07-24 11:35 UTC, BijanEisapour requested changes
تمام عکس‌ها باید فرمت webp داشته باشن و زیر 100 کیلوبایت باشن

2022-07-24 11:35 UTC, BijanEisapour commented on .github/workflows/deploy-main.yml
> +            - main
رو همه برنچ ها بذارید 
الان من میخوام بدونم کدی که دارم review میکنم تست‌هاش پاس میشه یا نه 
نباید مجبور باشم اول کد رو ببرم رو main بعد ازش تست بگیرم

2022-07-24 11:35 UTC, BijanEisapour commented on .github/workflows/deploy-main.yml
> +              run: npm install
npm ci 

تفاوتش با install رو تو کارگاه گفته‌ام

2022-07-24 11:35 UTC, BijanEisapour commented on .github/workflows/deploy-main.yml
> +jobs:
جاب تست کو پس؟

2022-07-24 11:35 UTC, BijanEisapour commented on .github/workflows/deploy-temp.yml
> +name: Deployment Workflow
این فایل پاک شه

2022-07-24 11:35 UTC, BijanEisapour commented on .gitignore
> +package-lock.json
اینا رو چرا دستکاری کردید؟
هر چی اون سایته بهتون داده رو عیناً copy/paste کنید 
اگه احتیاج به تغییر داشت، تَهِ فایل تغییرات لازم رو بنویسید

2022-07-24 11:35 UTC, BijanEisapour commented on .prettierignore
> +package-lock.json
بعد از اینکه نکته‌ای که در مورد gitignore گفتم رو اصلاح کردید، یادتون باشه این رو هم اصلاح کنید

2022-07-24 11:35 UTC, BijanEisapour commented on .stylelintrc.json
> +        "value-no-vendor-prefix": null,
این قانون لازم‌الاجراست 
برش گردونید به حالت عادی

2022-07-24 11:35 UTC, BijanEisapour commented on angular.json
> +        "boilera": {
تو کل فایل‌های پروژه دنبال کلمۀ boilera بگردید و اونو به اسم پروژۀ خودتون تغییر بدید

2022-07-24 11:35 UTC, BijanEisapour commented on angular.json
> +                        "styles": ["src/styles.scss", "src/assets/icons/fontawesome-pro-6.1.1-web/css/all.min.css"],
همیشه اول رفرنس پکیج‌ها رو بذارید بعد کد خودتون رو 
در غیر اینصورت اگه تو کدتون از اون پکیج استفاده کنید، نمیتونه پیداش کنه

2022-07-24 11:35 UTC, BijanEisapour commented on angular.json
> +                        "styles": ["src/styles.scss", "src/assets/fonts/Yekan/Yekan.css"],
چرا fontawesome رو اینجا نذاشتید؟
بعد چرا یکان رو اینجا گذاشتید ولی بالا نذاشتید؟

2022-07-24 11:35 UTC, BijanEisapour commented on angular.json
> +    "defaultProject": "boilera",
نمیگم

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.html
> +    <img id="image" [src]="game.sliderImageAddress" [alt]="game.title" />
انقد از آیدی استفاده نکنید
آیدی فقط واسه زمانیه که میخواید تاکید کنید از این المان فقط یه دونه داریم 
اینجور جاها باید از کلاس استفاده کنید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.html
> +        {{ game.avgRating.toFixed(1) }}
چنین کاری وظیفۀ شما نیست 
سرور باید تعداد رقم اعشار رو درست بفرسته 
شما فقط نمایشش بدید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +    max-block-size: 55vh;
از aspect-ratio استفاده کنید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +                -webkit-line-clamp: 2;
از vendor prefix استفاده نکنید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.html
> +    <div id="slides">
نمیگم

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.scss
> +        padding-block-start: 75px;
unit

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.scss
> +        gap: 6vw;
چرا انقد از vw استفاده میکنید؟
علتی داره که میخواید با تغییر عرض صفحه، استایل‌هاتون هم عوض شه؟

این کارتون باعث میشه یه سری جاها بدونِ اینکه متوجه شید مشکل بوجود بیاد
چون با تغییر سایز صفحه، متغیرهای زیادی داره عوض میشه

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.scss
> +        padding: 1%;
چرا آخه؟

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.ts
> +    private autoNextInterval!: number | null;
^

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.ts
> +        bullet.animate(
^

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/components/side-nav/side-nav.component.html
> +        <a href="#"><i class="far fa-house-heart" title="خانه"></i></a>
اولاً routerLink
ثانیاً چرا هشتگ؟ صفحه خانه رو که ساختید؛ خب بهش لینک بدید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/components/side-nav/side-nav.component.html
> +    <div class="all">
چه اسمیه؟
بعد اصن چه لزومی داره دورشون div بندازید؟
از margin auto استفاده کنید برای اینکه بینشون فاصله بیفته

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/components/side-nav/side-nav.component.scss
> +    border-left: hsl(212deg 43% 50% / 70%) solid;
logical

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/components/side-nav/side-nav.component.scss
> +    border-left: hsl(212deg 43% 50% / 70%) solid;
سایزش کو؟

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/header.component.scss
> +        #search {
برای selectکردن کامپوننت‌ها نیازی به آیدی نیست 
صرفاً اسمش رو بنویسید ... 
app-search-box

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/header.component.scss
> +            margin-right: auto;
logical

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/components/header/header.component.ts
> +    }
چه استفاده‌ای از این کردید؟

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/data/.gitkeep
> +}
چرا؟

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/models/game.ts
> +        public avgRating: number
از اختصار استفاده نکنید 
قشنگ بنویسید averageRating

اما جدای از این، اینجا بنویسید rating کفایت میکنه

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/models/game.ts
> +    public get sliderImageAddress(): string {
اسم قابل‌فهم‌تر بذارید 
مثلاً cover

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/models/user.ts
> +    public cart: Array<number> = [];
همیشه فیلدها رو بالای constructor بذارید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/pages/home/components/categories/categories.component.html
> +    <h2>بازی های پرطرفدار</h2>
از نیم‌فاصله استفاده کنید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/models/game.ts
> +        return `assets/images/games/${this.subtitle}/horizontal.webp`;
این داده‌ها از سمت بک میاد 
نباید خودتون generate کنید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/pages/home/components/categories/categories.component.ts
> +            image: 'assets/images/last-of-us.png',
چرا فرمت عکس‌ها یکسان نیست؟
همه جا از webp استفاده کنید

2022-07-24 11:35 UTC, BijanEisapour commented on src/app/pages/home/home.component.ts
> +    public generateSuggestionGames(): Array<Game> {
چرا؟
مستقیم مقداردهی میکردید دیگه 
نیازی به تابع نیست

2022-07-24 11:35 UTC, BijanEisapour commented on src/pallete.scss
> +    --color-gray-81: hsl(0deg 0% 81%);
یعنی واقعاً انقد نیازه دقیق باشه که نمیشه از 80 استفاده کرد؟

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +input:focus {
nest

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +    list-style: none;
اینو دیدم تو کدهاتون یه جا اومده بودید به یه li داده بودید 
استایل اون li رو پاک کنید، چون اضافیه

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +    font-size: 15px;
unit

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +        border-radius: 999px;
unit

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +.shiny-button {
کامپوننت شه

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +            background: linear-gradient(92.83deg, var(--gradient-color-1) 0%, var(--gradient-color-2) 100%);
tall it

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +            background: linear-gradient(92.83deg, var(--gradient-color-1) 0%, var(--gradient-color-2) 100%);
بعد این چه زاویه‌ایه؟
یه عدد خوب بدید

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +                linear-gradient(92.83deg, var(--gradient-color-1) 0, var(--gradient-color-2) 100%);
نمیگم

2022-07-24 11:35 UTC, BijanEisapour commented on src/styles.scss
> +            inset: 4px;
unit

2022-07-24 11:40 UTC, dorrin-sot commented on .stylelintrc.json
> +        "value-no-vendor-prefix": null,
ببخشید اخه اون line clamp داخل توضیحات اسلایدشو، نیاز به display: -webkit-box داره که stylelint ازش ایراد میگرفت

2022-07-24 12:00 UTC, dorrin-sot commented on src/app/models/game.ts
> +        return `assets/images/games/${this.subtitle}/horizontal.webp`;
ببخشید اینو بعدا هم مگه بصورت یه string pattern خاصی از بک نمیگیرم مثلا gamecdn.com/slideshow/:gameid: ؟

2022-07-24 12:10 UTC, dorrin-sot commented on src/app/components/carousel/carousel.component.scss
> +        gap: 6vw;
میخوایم وقتی عرض صفحه عوض میشه عرض اسلایدها هم یه درصد از صفحه رو بگیرن و بیرون نزنن. همینطور gap بینشون هم تغییر کنه جوری که همیشه اون یه کوچولو سمت چپ از اسلاید بعدی نشون داده بشه

2022-07-24 12:11 UTC, dorrin-sot commented on src/app/components/carousel-item/carousel-item.component.scss
> +                -webkit-line-clamp: 2;
ببخشید آخه راه دیگه‌ای نیست برای max-lines قرار دادن روی توضیحات

2022-07-24 12:19 UTC, dorrin-sot commented on src/styles.scss
> +            inset: 4px;
rem اشکال نداره؟

2022-07-24 12:23 UTC, dorrin-sot commented on src/app/components/carousel/carousel.component.html
> +    <div id="slides">
ببخشید آخه اینا دیگه واقعا یکدونه ن

2022-07-24 16:29 UTC, BijanEisapour approved these changes

2022-07-24 16:29 UTC, BijanEisapour commented on src/app/models/game.ts
> +        return `assets/images/games/${this.subtitle}/horizontal.webp`;
خیر

2022-07-24 16:29 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.scss
> +        gap: 6vw;
اگه مجبورید اشکال نداره ولی در کل توصیه نمیکنم

2022-07-24 16:29 UTC, BijanEisapour commented on src/app/components/carousel-item/carousel-item.component.scss
> +                -webkit-line-clamp: 2;
این تو مرورگرهای دیگه کار نمیکنه 
یه راه دیگه پیدا کنید یا اینکه کلاً بیخیالش شید

2022-07-24 16:29 UTC, BijanEisapour commented on .stylelintrc.json
> +        "value-no-vendor-prefix": null,
برای این که فقط تو یه سری مرورگر خاص این فیچر وجود داره 
جاهای دیگه کار نمیکنه و ظاهر سایتتون بهم میریزه

2022-07-24 16:40 UTC, dibaaamir approved these changes

2022-07-24 17:00 UTC, merged