background changed
Star-Academy/Summer1401-FE-Team01 pull request #6
Opened 2022-07-30 16:26 UTC by dorrin-sot

Fixes #5

2022-08-01 19:08 UTC, atareversei commented on src/app/components/auth/auth-form.scss
> +            width: 100%;
inline-size

2022-08-01 19:08 UTC, atareversei commented on src/app/components/auth/auth.component.scss
> +                cursor: pointer;
به نظر من اینجور استایل‌ها بهتره توی global باشه مثل cursor: pointer و border: none

2022-08-01 19:08 UTC, atareversei commented on src/app/components/auth/components/login/login.component.spec.ts
> +            declarations: [],
خالیه، میتونید پاک کنید

2022-08-01 19:08 UTC, atareversei commented on src/app/components/auth/components/register/register.component.html
> +        <app-input type="text" name="giver-name" label="نام" [(value)]="firstName"></app-input>
given-name نباید باشه؟

2022-08-01 19:08 UTC, atareversei commented on src/app/components/carousel-item/carousel-item.component.scss
>          box-sizing: border-box;
اینو توی استایل global ندارید؟

2022-08-01 19:08 UTC, atareversei commented on src/app/components/carousel/carousel.component.ts
> +        // );
کامنت

2022-08-01 19:08 UTC, AtaReversei commented on src/app/components/profile-button/profile-button.component.scss
> +                cursor: pointer;
این cursor: pointer رو خیلی تکرار کردید، تو component هم دارینش فکر کنم، بیشتر جاها میتونید حذف کنید

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/components/carousel/carousel.component.ts
> +        // );
کامنت اضافی پاک بشه

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.spec.ts
> +    let host: HTMLElement;
همون قبلی

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/components/header/components/search-box/search-box.component.scss
> +
این رنگ ها هم بهتره به پالت رنگیتون اضافه شه

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/components/header/components/search-box/search-box.component.scss
> +
در مورد این مقدار gap، فکرمیکنم اون نیم پیکسل زیاد تاثیر گذار نباشه. اگر به یه طرف متمایل شه عدده بهتر باشه

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/components/profile-button/profile-button.component.scss
> +
چون خوبی دارید صرفا به عنوان یه پیشنهاد میخوام بگم که میتونید به تگ های html تون مثل p یا h1 یا h2 یا ...به اینها فونت سایز ثابت و مشخصی بدید. بعد از اون تگ ها داخل html بسته به نیازتون استفاده کنید. با این کار هم استایل هایی که به عنوان fontsize میدید کاهش پیدا میکنه که خودش باعث خوانایی بیشتر کد میشه. هم اینکه کنترلتون روی فونت هاتون بیشتر میشه. در واقع منظورم اینه شبیه کاری که برای رنگ های داخل سایتتون کردید و براشون پالت درست کردید، برای فونت ها هم میشه یه همچین کاری انجام داد.

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/pages/home/components/categories/categories.component.html
> +                    <div class="overlay">
اگر تصویر بازی موضوعیت داره طوری که کاربر باید محتواش رو ببینه. سعی کنید توی alt محتوای تصویر رو توصیف کنید تا کاربران نابینا هم بتونن تا حدودی متوجه تصویر بشن. اگر هم موضوعیت نداره که همینی که نوشتید خوبه.

2022-08-01 19:23 UTC, Alirezab-2000 commented on src/app/pages/home/components/categories/categories.component.scss
> +                        }
فونت سایز مساوی 8 و نیم پیکسل؟ فکر نمیکنم با 8 یا 9 پیکسل زیاد فرق کنه.

2022-08-01 20:11 UTC, AtaReversei approved these changes

2022-08-01 20:39 UTC, Alirezab-2000 approved these changes

2022-08-02 05:56 UTC, dibaaamir approved these changes

2022-08-02 05:59 UTC, dibaaamir commented on src/app/components/profile-button/profile-button.component.scss
> +                cursor: pointer;
برای باتن ها این رو درست کردیم ولی بعضی جاها برای غیر از باتن ها مجبوریم این کارو بکنیم.

2022-08-02 07:19 UTC, SinaMAmini requested changes

2022-08-02 07:19 UTC, SinaMAmini commented on src/app/components/header/header.component.html
> +            <a href="/auth">
چرا href؟

2022-08-02 07:19 UTC, SinaMAmini commented on src/app/components/auth/components/login/login.component.html
>  </form>
بنظرم بهتره توی صفحه ورود و ثبت نام یه دکمه باشه برای برگشتن به سایت...

2022-08-02 07:19 UTC, SinaMAmini commented on src/app/components/header/header.component.html
> +            <a href="/auth">
حالا که href هست، حداقل forward slash (/) رو بر میداشتید که وقتی روش کلیک میکنیم توی gh-pages ارور 404 نده و بره تو صفحه ثبت نام...

2022-08-02 07:19 UTC, SinaMAmini commented on src/app/components/header/header.component.html
> +        <a href="/cart" class="icon-button">
این چیه؟؟

2022-08-02 07:19 UTC, SinaMAmini commented on src/app/components/header/header.component.html
> +            <i *ngIf="isLoggedIn" class="far fa-cart-shopping"></i>
به نظرم ngif باید برای پدرش باشه...
الان یه دکمه نا مرئی کنار دکمه ورود وجود داره

2022-08-02 07:19 UTC, SinaMAmini commented on src/app/components/footer/footer.component.html
>  </footer>
بنظرم بهتره برای واقعی تر شدن؛ اطلاعات بیشتری از شرکت داخل footer باشه

2022-08-02 07:43 UTC, dibaaamir commented on src/app/components/header/header.component.html
> +        <a href="/cart" class="icon-button">
سبد خرید برای وقتی که کاربر وارد شد

2022-08-02 08:02 UTC, SinaMAmini commented on src/app/components/header/header.component.html
> +        <a href="/cart" class="icon-button">
اینو وقتی وارد نشده بودم، دیدم و نفهمیدم چیه...
تو کامنت بعدی فهمیدم که چیه و البته ایرادشم گفتم.

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/auth/auth.component.scss
> +            h1 {
اصلا مگه داخل auth-switcher از h1 استفاده شده؟

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/auth/components/login/login.component.html
> +            type="outline"
جاش با خط بالا عوض بشه

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.html
> +            [title]="'انتخاب اسلاید ' + i"
این بره بالای خط کلیک

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/carousel/carousel.component.spec.ts
> +        testCurrentClassNames();
اگر احتیاج به کامنت برای initial index(0) داره خب 0 رو پاس بدید :)

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/footer/footer.component.html
> +        (click)="backToTopButtonClickHandler()"
این خط بیاد پایین پایین

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/header/components/search-box/search-box.component.html
> +        (keydown.enter)="submitSearch(input)"
بیاد زیر ngModel

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/header/header.component.ts
>  import {Component} from '@angular/core';
چرا خود header تست نداره؟

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/input/input.component.spec.ts
> +    });
تابع dir قابلیت تست نداشت؟

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/components/profile-button/profile-button.component.ts
> +        this.authService.logout().then();
چرا then؟ چرا async await نه؟

2022-08-02 09:35 UTC, sabaebrahimi commented on src/app/guards/auth.guard.spec.ts
> +            it(`tests ${path == '/profile' ? 'accept' : 'reject'} if navigating to ${path}`, async () => {
===

2022-08-02 09:40 UTC, HessamCheraghi requested changes

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/components/auth/components/login/login.component.spec.ts
> +import {ProfileComponent} from '../../../profile/profile.component';
اینجا به جای `../..` بهتره از absolute path استفاده کنید

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/components/auth/components/register/register.component.spec.ts
> +import {SnackbarServiceMock} from '../../../../mocks/snackbar-service.mock';
گفتم

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/components/auth/components/register/register.component.spec.ts
> +        });
اینجا بهتر نیست که توی یه تابع جداگونه بزارید و بعد status رو بهش پاس بدید؟

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/components/auth/components/register/register.component.spec.ts
> +    for (let status of firstLastNameStatuses) {
اینجا باید `const` باشه

```javascript
for (const status of firstLastNameStatuses) {
//code
}

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/components/carousel-item/carousel-item.component.spec.ts
> +describe('CarouselItemComponent', () => {});
اینجا تستی ننوشتید؟

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/components/carousel/carousel.component.spec.ts
> +        // initial index (0)
کامنت ها بهتره پاک بشه

2022-08-02 09:40 UTC, HessamCheraghi commented on src/app/guards/auth.guard.spec.ts
> +        for (let path of ['/auth', '/profile']) {
گفتم

2022-08-02 09:43 UTC, dibaaamir commented on src/app/components/carousel/carousel.component.spec.ts
> +        // initial index (0)
چون یکم پیچیده بود کامنت گذاشتیم برای تفهیم بهتر

2022-08-02 09:44 UTC, dibaaamir commented on src/app/components/auth/components/login/login.component.spec.ts
> +import {ProfileComponent} from '../../../profile/profile.component';
اینو خود webstorm به صورت دیفالت گذاشته اخه ما وارد نکردیم

2022-08-02 10:29 UTC, dorrin-sot commented on src/app/components/auth/components/register/register.component.spec.ts
> +        });
آخه یجا کلا داریم استفاده اش میکنیم. معلوم هم هست داره چیکار میکنه

2022-08-02 10:47 UTC, dibaaamir commented on src/app/components/footer/footer.component.html
>  </footer>
اخه سری اول لینک داشتیم به اینستا و تلگرام و اینا و اقای عیسی پور گفتن پاک کنین اگر استفاده ای نمیشه. برای همین دیگه به همین بسنده کردیم

2022-08-02 10:53 UTC, SinaMAmini approved these changes

2022-08-02 11:00 UTC, sabaebrahimi approved these changes

2022-08-02 11:14 UTC, HessamCheraghi approved these changes

2022-08-02 11:57 UTC, AliZoghi reviewed
بعضی کامپنتت ها تست نشدن.
 به عنوان مثال apiService

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/auth.module.ts
>  import {AuthComponent} from './auth.component';
وقتی از این کامپنتت داخل routing module استفاده میکنید، برای معماری بهتر، بهتره که داخل app/pages نوشته بشه

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/auth.component.html
>              <ng-container *ngIf="isInLoginView; else register">
وقتی از ngIf استفاده میکنید بهتره حالت رندر شدن یا نشدنشو داخل فایل تست، امتحان کنید.

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/auth.component.spec.ts
> +    it('tests create', () => {
تابع toggleIsInLoginView تست نشده

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/components/login/login.component.html
> +        [required]="true"
وقتی براش متغیری تعریف نشده و همیشه true بر میگردونه چرا از required خالی استفاده نمیکنید؟

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/components/register/register.component.html
> +    <app-input type="text" name="username" label="نام کاربری" [required]="true" [(value)]="username"></app-input>
نمیگم

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/components/login/login.component.html
> +    <app-input
^

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/auth/components/login/login.component.html
> +    <app-input type="password" name="password" label="رمزعبور" [required]="true" [(value)]="password"></app-input>
^

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/button/button.component.spec.ts
> +        expect(button?.className).toEqual(type || 'contained');
اگه کدتون درست کار کنه نیاز به نوشتن contained نداره

2022-08-02 11:57 UTC, AliZoghi commented on src/app/components/button/button.component.spec.ts
> +        expect(button?.className).toEqual(type || 'contained');
^

2022-08-03 05:38 UTC, AliZoghi approved these changes

2022-08-06 13:35 UTC, BijanEisapour requested changes
عکس پروفایل svg بشه

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/auth/auth.component.scss
> +            flex-direction: row;
x

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/auth/auth.component.scss
> +            }
بذارید همون پایین که button و a نوشتید 
همیشه explicit باشید مگر زمانی که مجبور شدید

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/auth/components/login/login.component.html
> +        <app-button text="ورود" (click)="formSubmitHandler()"></app-button>
بهتره رو form بیاید submit رو listen کنید 
اینجوری خواناییش بهتره 
آدم همون اول متوجه میشه اگه submit شد کدوم متد صدا زده میشه و دیگه نیازی نیس تا این پایین بیاد و بین کدها بگرده

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +    z-index: 0;
چرا؟

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +    }
همیشه موقع hover باید contrast رو بیشتر کنید

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +    }
پیشنهاد میکنم رنگ پس‌زمینه رو عوض کنید

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/button/button.component.ts
> +    @Input() public type: 'text' | 'outline' | 'contained' = 'contained';
enum

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/button/button.component.ts
> +    @Input() public type: 'text' | 'outline' | 'contained' = 'contained';
اسمش بهتره type نباشه چون منظور رو نمیرسونه
بذارید theme مثلاً

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.html
> +            (click)="setIndexByClick(i)"
اسم بهتر 
مثلاً bulletClickHandler

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.ts
> +    private doBulletAnimation(index: number, addClass: boolean): void {
واسه انیمیشن معمولاً از play استفاده میکنن

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/carousel/carousel.component.ts
> +                {duration: 300, easing: 'ease-in'}
عدد رو همینجوری لخت رها نکنید 
واسش مثه SLIDE_TIMEOUT، متغیر بسازید

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +    border: solid 1px var(--border-color);
رنگش تو حالت outline زیاد جالب نیس 
شاید اگه نارنجی بود بهتر میشد

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/input/input.component.scss
> +        background-color: var(--color-background-20);
این حرکت شاید جالب به نظر برسه ولی خطریه 
اگه فرم رو بخواید با یه پس‌زمینۀ دیگه نشون بدید چی؟
یا اگه خودِ مرورگر فیلدها رو پُر کنه یه پس‌زمینۀ آبی بهش میده؛ اون موقع میزنه تو ذوق

2022-08-06 13:35 UTC, BijanEisapour commented on src/app/components/input/input.component.ts
> +    }
بذارید هر کی از کامپوننت استفاده میکنه خودش تصمیم بگیره dir چی باشه 
تبدیلش کنید به Input

2022-08-06 18:20 UTC, dorrin-sot commented on src/app/components/button/button.component.ts
> +    @Input() public type: 'text' | 'outline' | 'contained' = 'contained';
ببخشید اشکال نداره enum نزاریم؟ چون اونطوری هی هرجا یه app-button داریم باید توی فایل تایپ‌اسکریپت‌ش یه const ButtonTheme = ButtonTheme بزاریم

2022-08-07 01:20 UTC, BijanEisapour approved these changes

2022-08-07 01:20 UTC, BijanEisapour commented on src/app/components/button/button.component.scss
> +        // --border-color: var(--color-background-85);
x

2022-08-07 01:20 UTC, BijanEisapour commented on src/app/components/input/input.component.scss
> +                /* stylelint-disable property-no-vendor-prefix */
آیا این نیازه؟

2022-08-07 01:20 UTC, BijanEisapour commented on src/app/components/input/input.component.scss
> +        &:-webkit-autofill {
بقیه مرورگرها بدون prefix ساپورتش میکنن 
واسه اونا هم بذارید

2022-08-07 06:33 UTC, dorrin-sot commented on src/app/components/input/input.component.scss
> +                /* stylelint-disable property-no-vendor-prefix */
ایراد میگیره آخه :(

2022-08-07 07:46 UTC, merged